title: Mirgfhfhhfganda Auriemma
description: Technical Artist and Engineer
# descriptionExtra: haha does is work?
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
page_excerpts: true

# collections_dir: collections
collections:
  portfolio_pages:
    output: true
# collections:
#   animals:
#     output: true