title: Miranda Auriemma
description: Technical Artist and Engineer
# descriptionExtra: haha does is work?
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
page_excerpts: true

collections:
  portfolio_pages:
    output: true
