title: Miranda Auriemma
description: Technical Artist and Engineer
# descriptionExtra: haha does is work?
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
page_excerpts: true

collections:
  portfolio_pages:
    # order: # (cant use this until i figure out how to get jekyll 4.0 to work with github pages. I want to keep this updated anyway as an ongoing record of intended order)
    # - channel-getaway.md
    # - dx12-raymarcher.md
    # - brave-magnet.md
    # - raymarcher-ue4.md
    # - particle-system.md
    # - kanji-helper.md
    output: true

external_links:
  twitter: "REMOVE ME"
  tumblr: "https://www.tumblr.com/random-access-garlic"
  linkedin: "https://www.linkedin.com/in/miranda-auriemma"
  github: "https://github.com/tafellappen"
  mail: "mailto:msa4295@rit.edu"
  kanji_helper: "https://people.rit.edu/msa4295/kanji/dist/"
  getaway: "https://milesmichell.itch.io/channel-getaway"
